spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    # url: jdbc:mysql://localhost:3306/user_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8090

springdoc:
  swagger-ui:
    operations-sorter: method
