spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    # url: jdbc:mysql://localhost:3306/user_db
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8090
